### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by jdittrich** [simonv3/quick-survey#16]
**Story**: As a User Researcher I want to try quickly if the tool suites my needs

**What currently happens**: I need to deploy to Heroku or set it up via Meteor. Both are not too difficult, but given that many UX researchers have no or limited coding skills this might be a blocker. 

**What should happen:** A demo website where one can try out the software should be accessible via a link.

**Comment by RichardLitt** [comment]
:+1:

**Comment by simonv3** [comment]
Good stuff. Yeah, I can set up a demo site pretty easily. Guess I can just say "here's the admin login"?

**Comment by jdittrich** [comment]
I think yes. Makes sense to reset it daily or the like, in case someone administrates around too much.

**Comment by simonv3** [comment]
Hehe "someone administrates around too much" <- critique of Life.

Yeah I wonder if that's possible to do with meteor or Heroku.

**Comment by simonv3** [comment]
Just an update on this: I've packaged this for Sandstorm and sent it to their servers so that it can be verified. This would mean that you can try the app itself - I think without needing a sandstorm account, but possibly with.

**Comment by simonv3** [comment]
Have a look here for the Sandstorm [demo](https://apps.sandstorm.io/app/wupmzqk4872vgsye9t9x5dmrdw17mad97dk21jvcm2ph4jataze0). I'll add this to the readme.

**Comment by jdittrich** [comment]
Works greatly.

**Comment by simonv3** [comment]
more improvements to come!
