### ISSUE TITLE
Enable downloading CSV on Sandstorm

### ISSUE THREAD

**Issue by simonv3** [simonv3/quick-survey#19]
This doesn't work, and it errors when clicked.

**Comment by qznc** [comment]
I don't even see a link to click. The feature is important, though.

**Comment by simonv3** [comment]
@qznc I think I removed the link to it until it works. I have an inkling that this should be doable purely in the front-end so that might be a path to go down.

**Comment by simonv3** [comment]
This functionality looks like it disappeared. Why?
