### ISSUE TITLE
Save button resets survey description [sandstorm]

### ISSUE THREAD

**Issue by JamborJan** [simonv3/quick-survey#27]
I'm using quick survey on sandstorm.io

When creating a new grain and giving a name, description and end text to the survey I click the save button. The survey is reset and not saved.

Tested with mobile safari browser on iOS 9.

**Comment by JamborJan** [comment]
Same happens when adding a first question to the survey and then clicking the "create question" button. The 3 basic input fields of the survey are reset, nothing is saved.

**Comment by simonv3** [comment]
@JamborJan That seems pretty fundamentally broken. I haven't had a chance to test this on mobile devices yet, but will do so when I get a hold of one. Thanks for reporting!

I'm wondering if it's a permissions issue.

Have you had a chance to create a survey on a non-mobile browser and then fill in the survey results on a mobile browser? That would be pretty bad if it didn't work.

**Comment by JamborJan** [comment]
Hi @simonv3 yes I can answer to a survey but the screen is stuck in a wired situation. It shows "Thanks! Just finishing up ..."

One important thing: I use 3rd party blockers on my mobile (1Blocker for iOS). I disabled it but it doesn't solve the problem

**Comment by simonv3** [comment]
Odd, and does it show the answer you just submitted on the "manage" screen when you're on the desktop viewer?

**Comment by JamborJan** [comment]
yes it does.

**Comment by simonv3** [comment]
Cool, I'll have to test that locally to figure out what's going wrong then. Hopefully it's an easy fix.

**Comment by JamborJan** [comment]
Unfortunately I have only little time so I cannot give you more details, logs or test results. Sorry. Hope you find a solution.

**Comment by simonv3** [comment]
No worries! Definitely thanks for trying out Quick-Survey and for reporting an issue. I hope I can figure it out!
