### ISSUE TITLE
Demo website asking for email verification

### ISSUE THREAD

**Issue by hackbinary** [simonv3/quick-survey#29]
The admin@admin.com login is asking for an email verification, and saying that an email has been sent.

Also, admin.com is an actual domain.  You should use `example.com` for examples such as this.

**Comment by simonv3** [comment]
Gah, yeah, forgot about that. I'll fix it when I get a chance. Thanks for reporting!

Edit: In the meantime, you can use the sandstorm app: https://apps.sandstorm.io/app/wupmzqk4872vgsye9t9x5dmrdw17mad97dk21jvcm2ph4jataze0

**Comment by simonv3** [comment]
Got rid of this with only allowing Sandstorm.
