### ISSUE TITLE
QuickSurvey on Sandstorm

### ISSUE THREAD

**Issue by jResponse** [simonv3/quick-survey#30]
QuickSurvey on Sandstorm does not appear to have a mechanism to lock the survey in "Survey Only" mode when it shared with others on SandStorm.  Allowing "surveyees" to modify the survey is not at all what is desired when conducting a survey!

**Comment by simonv3** [comment]
Thanks for the bug report @jResponse! 

I'm having some issues replicating this. For example, if I access this survey in anonymous mode: 

https://oasis.sandstorm.io/shared/F37UNv7mBAlWH_JOh_lne8cTAdGMDCFdlxGf2-pxdPa/admin

I can't access the manage menu. 

Could you give some more details about your browser / how you came across this issue?

**Comment by jResponse** [comment]
Simon - I run into the issue on my own, privately hosted, Sandstorm server - not oasis. I will share a link to it via email.

**Comment by simonv3** [comment]
From the e-mail conversation (IIRC) this has been fixed. I'm also going to guess that simplifying the log in system and focusing on Sandstorm only will have helped.
