### ISSUE TITLE
Pretty URL for sharing

### ISSUE THREAD

**Issue by zeigerpuppy** [simonv3/quick-survey#35]
The current sharing URLs are not very easy for people to input,
It may be good to include some instructions of how to create a prettier URL.
I have used a nginx redirect which works well.
Some sort of email tracking may be nice too, so that users have their email field inputted straight away into the survey if it was sent from a bulk email.

```
    location = /survey {
    return 301 /shared/LlBubZh_U7349GHKiik5aCJambHPYFtUxNdpjs;
    }
```

**Comment by simonv3** [comment]
Hey @zeigerpuppy, thanks for the thoughts!

I'm assuming this is all in the context of Sandstorm?

If so, the sharing URL is defined by Sandstorm, not by Quick-Survey. You can use a URL shortener if you want something more concise - though they're talking about having their own sharing service, and the URL thing comes up pretty regularly.

If you're not talking about Sandstorm, it's self hosted so you can just use whatever domain name you want - unless you mean to prettify the Heroku name?

Could you open a second issue for the "email tracking" feature you suggest and outline it a bit more?

**Comment by elimisteve** [comment]
@zeigerpuppy I also want prettier URLs for all Sandstorm apps, but this is not something apps can control. As Simon says :-D, "[y]ou can use a URL shortener if you want something more concise", so hand https://apps.sandstorm.io/app/wupmzqk4872vgsye9t9x5dmrdw17mad97dk21jvcm2ph4jataze0 or a similarly nasty URL to https://bit.ly and it'll be much shorter!

**Comment by zeigerpuppy** [comment]
The problem with URL shorteners is that they track usage through the redirect.
Eventually it may be good to have a URL shortener built into sandstorm, but I know this isn't the place to raise that.
What may be good for the quick-survey port however, is an instruction page that says how to share the survey:

For instance:

### To share privately,
- use the sandstorm "Share Access" feature and share with your contacts

### To share a survey for the public
- create a "shareable link" from the "Share Access" menu
- this URL would then be the one to shorten

**Comment by simonv3** [comment]
Hey @zeigerpuppy. That's a good idea. I thought there was already (I'll have to double check, it's been a while) something super basic in place for that, so it wouldn't be too hard to expand on it. 

When you set up the survey, you have the option of showing a "share" link. When users click on that link the Sandstorm UI for sharing pops up. Some more instructions there would probably be good as well until that becomes a better understood pattern.
