### ISSUE TITLE
Shared users don't see "manage" interface (sandstorm)

### ISSUE THREAD

**Issue by zeigerpuppy** [simonv3/quick-survey#37]
When sharing a form, it looks like shared users are treated as non-admin
It would be good for a sandstorm user to be able to share management with a second user
while still having the public access to the form as submit only.

**Comment by simonv3** [comment]
100% agreed. This is definitely on the roadmap in my head. Now it is so publicly too.

I think I need to commit Quick-Survey to be Sandstorm only, this will make these kind of logic things much easier and more maintained.
