### ISSUE TITLE
How can i get admin permission. Create surveys?

### ISSUE THREAD

**Issue by dimti** [simonv3/quick-survey#40]
http://i.imgur.com/fj9H6ec.png

I install with git clone and launch with meteor

Any attempts creating account with my private email, and change with robomongo to admin@ emails - not result

App in sandstorm also without buttons in top-left area for management and viewing surveys

**Comment by simonv3** [comment]
@dimti what happens when you go to the `/manage` URL?

**Comment by dimti** [comment]
If i get /manage then redirect to base url / on any accounts (first created and in admin@*)

**Comment by simonv3** [comment]
Are you running this on a local server?

**Comment by dimti** [comment]
on survey.wpstudio.ru

**Comment by dimti** [comment]
http://i.imgur.com/B5AXxzP.png

**Comment by simonv3** [comment]
Hey dimti, I'm not sure in what environment you're running in.

For my own sanity I recently made the decision to only support Sandstorm. It will make development a lot easier and avoid a ton of headaches. Is this happening within Sandstorm?

**Comment by dimti** [comment]
On sandstorm - i fetched admin page. but i not see manage buttons on top panel

After that, i think - setup on my archlinux server. But, on dedicated server - surveys app not have admin permissions and also i not see manage buttons on top panel.

Today - on sandstorm - manage buttons i see.

On dedic server, after update develop branch from 6c7d7cb to 254fe19. I unable login into system - i not see login button anywhere

If i checkout on sandstorm branch, i can run survey app as default meteor application or me need setup sandstorm on my server?

What is sandstorm (tehnically)?

**Comment by simonv3** [comment]
The `sandstorm` branch is out of date and no longer valid. The `develop` branch is the main branch and is only for Sandstorm now.

You'll have to set up Sandstorm on your own server if you want to run Quick Survey without hacking on the code. Feel free to create your own fork of Quick Survey if you do want to run it outside of Sandstorm. What you would have to add is exactly what you're missing - user and log in information. 

If you want to test locally but not make modifications on the code have a look at https://github.com/sandstorm-io/meteor-accounts-sandstorm, where it's explained how you can create a "mock" user to pretend you're on Sandstorm.

I'll let the Sandstorm website describe what sandstorm is properly: https://sandstorm.io/, but in a nutshell Sandstorm is server infrastructure that you can install on your own server, or use from someone else that lets you install a series of compartmentalized web apps.

**Comment by simonv3** [comment]
Hey @dimti, I'm going to mark this as closed. Let me know if you have any more questions!
