### ISSUE TITLE
Changing between checkboxes and radio buttons should keep the list of options.

### ISSUE THREAD

**Issue by gwillen** [simonv3/quick-survey#42]
It's easy to pick the wrong type by accident. I'm pretty sure that on Google surveys, you can switch between them and keep the options, whereas this one wipes them. I realize it doesn't _exactly_ make semantic sense since the different question types have different meanings... but it's super useful when you aren't paying close attention to which one you picked.

**Comment by simonv3** [comment]
Yeah, this makes sense. I just hadn't thought of it.

**Comment by gwillen** [comment]
Yay, thank you! :D

**Comment by simonv3** [comment]
Still need to package and release, but I've been having some issues with Meteor the past two days, sorry :/
