### ISSUE TITLE
Can't remove empty checkbox

### ISSUE THREAD

**Issue by neynah** [simonv3/quick-survey#43]
I accidentally made one too many checkbox options but can't get rid of the extra one without deleting the question.
![image](https://cloud.githubusercontent.com/assets/855341/18848886/422bdf16-83e5-11e6-83a7-4f30ef07a30f.png)

**Comment by simonv3** [comment]
@neynah thanks for reporting - this should be a relatively easy fix - what do you expect here? An (x) on the right?

**Comment by neynah** [comment]
> @neynah thanks for reporting - this should be a relatively easy fix - what do you expect here? An (x) on the right?

Yeah I think that would be appropriate. Either that or upon save it just ignores checkbox options that have no labels. Thanks!

**Comment by simonv3** [comment]
Ooh, I like that suggestion as well.
