### ISSUE TITLE
When answering freeform 'other' multiple select option, hitting enter prematurely submits survey

### ISSUE THREAD

**Issue by mairin** [simonv3/quick-survey#46]
While running a survey today, I got a complaint that someone tried to fill out an 'other' multiple choice option and fill in some text in the text field next to 'other' - when they finished typing that text they hit enter and that submitted the survey rather than submitted their 'other' text entry. Maybe making enter hits not hit the survey when focus is on a text field / text area would help?

**Comment by simonv3** [comment]
That sounds like a good idea. I don't know whether "enter" should map to submitting the survey at all.

**Comment by simonv3** [comment]
This will be fixed in the next release of Quick Survey :)
