### ISSUE TITLE
RFE: reordering questions

### ISSUE THREAD

**Issue by mairin** [simonv3/quick-survey#48]
It would be really nice to be able to reorder the questions without having to delete and retype them!

**Comment by suzannehillman** [comment]
Yeah, I just ran into this myself. Please add this!

**Comment by amca01** [comment]
I agree - this would be a very useful addition.

**Comment by simonv3** [comment]
This will be implemented in the next release of quick survey :)

**Comment by mermaidz** [comment]
Hey all, would you know if this ever happened to be implemented since then?

**Comment by simonv3** [comment]
@mermaidz it's implemented, but might not be released on sandstorm?

**Comment by mermaidz** [comment]
Thank you for such a fast answer, @simonv3 . I'm relatively new at sandstorm, is there any way I can access an implemented feature if this has not been released there?
