### ISSUE TITLE
Cannot edit the text of 'other' options.

### ISSUE THREAD

**Issue by suzannehillman** [simonv3/quick-survey#49]
I have found that people can find the term 'other' in surveys to be, well, 'other-ing'. It can make surveys not especially approachable, and can turn people whose opinions aren't necessarily the same as is common off from filling out the survey.

Is it possible to allow survey creators to edit the text of 'other', so that I can adjust it to be something like 'something else', instead? Thanks!

**Comment by simonv3** [comment]
👍  That makes a lot of sense. Do you have an idea of what that flow might look like?

**Comment by suzannehillman** [comment]
If by flow, how I imagine it working, yes:

I add an 'other' option, and if I click on the 'other' word, I can edit it.
Saving could be automatic as soon as I select elsewhere on the page, or it
could involve an actual save button. I think the former would go with my
general expectations of how websites work nowadays.

Thanks!

**Comment by simonv3** [comment]
This will be in the next release of Quick-Survey!
