### ISSUE TITLE
Don't allow admin to save without a minimum of 2 radio options.

### ISSUE THREAD

**Issue by neynah** [simonv3/quick-survey#51]
Radio questions can be "successfully" created without having added a minimum of 2 radio options. The ideal behaviour should be that the survey admin should not be able to save the survey without having provided 2 options for radio selection.

Steps to reproduce (Admin):
- Create new Sandstorm grain of Quick Survey.
- Add new question, select the "Radio" input type option in the dropdown menu.
- Without adding any radio options, save the survey.

View as a respondent:
- "Share Access" to the survey by specifying permissions as "Can fill survey" and creating a sharing link.
- Open sharing link in incognito or another account that does not have Admin privileges to this grain.
- You'll see that the radio question will show up, however, there are no affordances for any action

Screenshot of survey with 0 radio options:
![image](https://cloud.githubusercontent.com/assets/855341/20242479/2f88604a-a8e4-11e6-97ea-37ae8729e7cf.png)

Screenshot of survey with 1 radio option:
![image](https://cloud.githubusercontent.com/assets/855341/20242494/8fcb83d8-a8e4-11e6-818c-520264a1a515.png)

**Comment by simonv3** [comment]
This will be in the next release :)
