### ISSUE TITLE
sandstrom login credentials

### ISSUE THREAD

**Issue by frankwo1** [simonv3/quick-survey#61]
Hi - can you tell me where I set up the "fake sandstorm" login credentials if I'm running this locally on meteor - I can't seem to find out where to put this?
e.g. SandstormAccounts.setTestUserInfo({
  id: "12345",
  name: "Alice",
  // ... other parameters, as listed above ...
});
Thanks
Frank

**Comment by simonv3** [comment]
In the console in your browser should work fine IIRC.

**Comment by frankwo1** [comment]
Thanks - it inserts into mongo but I'm not sure how to give myself admin privileges - just not familiar enough with sandstorm - can u help with string ...
SandstormAccounts.setTestUserInfo({id: "12345",name: "Alice", permissions: [name: "admin"]});

**Comment by simonv3** [comment]
I think: 

```
SandstormAccounts.setTestUserInfo({
  id: 1,
  name: "Alice",
  permissions: ['owner']
});
```

**Comment by simonv3** [comment]
Just added some instructions to the README.md, let me know if they work:

https://github.com/simonv3/quick-survey/commit/8d701119adbb07fd44a78b2d53c722a2f682301b

**Comment by frankwo1** [comment]
That works - thanks
Just not enough info on sandstorm

**Comment by simonv3** [comment]
That's actually on my end, the permission levels are defined by the app itself, not by sandstorm. You can see the full list here: https://github.com/simonv3/quick-survey/blob/develop/.sandstorm/sandstorm-pkgdef.capnp#L155
