### ISSUE TITLE
Submit button stutters (= this app is NOT cooked!! fix it or unpublish it!!)

### ISSUE THREAD

**Issue by pzelchenko** [simonv3/quick-survey#67]
Simon, if you can't reasonably support your existing software, then perhaps you should either consider not starting new projects, or unpublishing faulty projects. Second issue today: People are having trouble clicking Submit on your survey, and so they hammer on the button. Guess what? I've got 40 surveys from one person. That's just wrong.

**Comment by simonv3** [comment]
Still an asshole.
