### ISSUE TITLE
I'm going to recommend that this piece of junk app be deleted from Sandstorm

### ISSUE THREAD

**Issue by pzelchenko** [simonv3/quick-survey#68]
![image](https://user-images.githubusercontent.com/7409590/32492140-3cd9627c-c3f4-11e7-869a-5b61d24af799.png)
Either you disallow commas in text fields (not so good), or you escape text fields with quotes for CSV download (best option). This is basic behavior, should take five minutes either way, and you didn't implement it. Thank goodness I noticed, otherwise my data would have been toast thanks to you. And yet I am now still going to have to spend three hours fixing the shit CSV you've given me. This is not software that should be released. It's 100% garbage.

**Comment by simonv3** [comment]
Wow you're an asshole.
