### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by pzelchenko** [simonv3/quick-survey#69]
You didn't repair my issues, you closed them. That's censorship. Congratulations. Because of your slacker nature, you're going to cause a lot more people to suffer rather than warn people of your app's enormously time-consuming deficiencies. I lost six hours of my day because of your lack of responsibility. Now others will follow.

You've now turned someone who merely disliked you and your practices into an enemy. If I have anything, ever, to say about any of your products in the future, I will be sure to do so. Unless you commit to supporting them or finding someone who can, I am going to make sure that your apps with significant problems are unpublished on every site I can find. This product does not deserve to exist anymore.

**Comment by pzelchenko** [comment]
Incidentally, humanitarian aid starts at home, in the workplace, in a sense of conscience. I don't know what's distracting you from actually helping people -- maybe saving the whales or getting clean syringes to the Third World -- but a lot of people can do that. Thinking about your users' struggle with your creation and acting on it is something ONLY YOU can do, and you choose instead to be distracted by other projects. You appear to enjoy a monopoly on survey apps in Sandstorm. Fix your app or find someone who can, or put some warnings up as to the lack of functionality of your app, or else take the app down and get out of the survey software business, leaving someone who cares about his or her users to make a survey product whose most basic functions actually do what they should (Submit button feedback, non-stuttering Submit button, and proper comma handling in CSV).

**Comment by simonv3** [comment]
![screenshot 2017-11-07 08 15 27](https://user-images.githubusercontent.com/485583/32504106-e145c122-c393-11e7-8ad8-6a0aea5d99f6.png)

slow clap. 

You're more than welcome to put in a PR to the readme to say that this app doesn't work as you expected. Or better yet, put in a PR to fix the issues.

**Comment by currymj** [comment]
420 y’all lmao
